Feat/book
jeonghwan951204/publisher pull request #4
Opened 2022-01-03 08:22 UTC by jeonghwan951204

## Motivation

- 사용자별 환경 구분
- bookRepository,bookRepositoryCustom,bookRepositoryImpl,BookService 추가
- BookApiController insert api테스트

<br>

## Key Changes

- 추가한 Book 클래스
 
![image](https://user-images.githubusercontent.com/70299627/147910868-1f8bdecb-be8e-406d-9cb4-ae0da04289cf.png)

<br>

## To Reviewers

- replace this persistent entity with a simple pojo or dto object 이슈 파악

<br>

2022-01-03 11:36 UTC, jhy950210 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-websocket:2.5.7'
web으로 돌려놓기

2022-01-03 11:42 UTC, jhy950210 commented on src/main/java/com/book/publisher/api/BookApiController.java
> +    @PostMapping(value = "/bookInsert")
POST /book

2022-01-03 11:44 UTC, jhy950210 commented on src/main/java/com/book/publisher/entity/Book.java
> +    @Column(columnDefinition = "timestamp(0)")
@CreatedDate -> 생성 날짜 자동 생성

2022-01-03 12:17 UTC, jhy950210 requested changes
good

2022-01-04 04:46 UTC, merged

2022-01-04 04:51 UTC, jeonghwan951204 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-websocket:2.5.7'
web으로 바꾸고 2.5.7버전 명시

2022-01-04 04:52 UTC, jeonghwan951204 commented on src/main/java/com/book/publisher/api/BookApiController.java
> +    @PostMapping(value = "/bookInsert")
url 변경

2022-01-04 04:53 UTC, jeonghwan951204 commented on src/main/java/com/book/publisher/entity/Book.java
> +    @Column(columnDefinition = "timestamp(0)")
@CreateDate로 변경